sudo: required

language: generic

matrix:
  include:
    - os: linux
      env: COMPILER=4.02.3
    - os: linux
      env: COMPILER=4.03.0
    - os: linux
      env: COMPILER=4.04.2
    - os: linux
      env: COMPILER=4.05.0
    - os: linux
      env: COMPILER=4.06.1
    - os: linux
      env: COMPILER=4.07.1
    - os: linux
      env: COMPILER=4.08.0
    - os: osx
      env: COMPILER=4.08.0

script: bash -e src/travis.sh

notifications:
  email:
    recipients:
      - antonbachin@yahoo.com
    on_success: always
    on_failure: always
